global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'juno'
    static_configs:
      - targets: ['node:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
