name: Production Deploy

on:
  push:
    branches: [main]
    
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  # On PR, attempt to build the docs normally
  test-docs-build:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - uses: mskelton/setup-yarn@v1
        with:
          node-version-file: '.nvmrc' 
          cache: 'yarn'
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Test Build
        run: |
          cd docs
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
          npm run build
  
  # When pushing to main, deploy docs to production (gh-pages)
  gh-release:
    if: github.event_name == 'push' && {{ !env.ACT }}
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: http://gojuno.xyz
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
      - uses: actions/setup-node@v3
        with:
          node-version-file: 'docs/.nvmrc'
      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY }}
      - name: Release to GitHub Pages
        env:
          USE_SSH: true
          GIT_USER: git
          CURRENT_BRANCH: ${{ secrets.CURRENT_BRANCH }}
          TARGET_URL: "http://gojuno.xyz/"
          BASE_URL: "/"
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "gh-actions"
          cd docs
          cp .env.template .env 
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
          npm run deploy
