name: Juno Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.18' ]
    name: Juno with Go ${{ matrix.go }}
    steps:
      - uses: actions/checkout@v2
      - name: Run Juno
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: make all
