name: Juno Static Checks
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.18' ]
    name: Juno with Go ${{ matrix.go }}
    steps:
      - uses: actions/checkout@v2
      - name: Build Juno
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - run: make compile

      - name: Install gofumpt
        run: make install-gofumpt

      - name: Run gofumpt
        run: make format-check