name: RPC Tests

on:
  workflow_dispatch:
    inputs:
      NODE_ADDRESS:
        description: 'Target Node Address, e.g http://IP_ADDRESS:PORT'
        required: true
      NETWORK:
        description: 'Target Network'
        required: true
        default: 'mainnet'

jobs:
  RPC_Tests:
    name: RPC Test Execution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Juno Smoke Tests
        uses: actions/checkout@v3.5.2
        with:
          repository: NethermindEth/juno-smoke-tests
          token: ${{ secrets.REPOSITORY_DISPATCH_TOKEN }}

      - name: Setup Go Environment
        uses: actions/setup-go@v4.1.0
        with:
          go-version-file: rpc-tests/go.mod

      - name: Execute RPC Tests
        working-directory: rpc-tests/tests
        run: go test -v --nodeURL=${{ github.event.inputs.NODE_ADDRESS }} --network=${{ github.event.inputs.NETWORK }}