name: run node on new vm

on:
  workflow_dispatch:
    inputs:
      network:
        description: 'Network'
        required: false
        default: 'mainnet'
        enum: ['mainnet', 'sepolia', 'sepolia-integration']
  schedule:
    - cron: '0 22 * * 5'

jobs:
  run_node_on_new_vm:
    runs-on: ubuntu-latest
    env:
      NETWORK: ${{ github.event.inputs.network || 'mainnet' }}
    steps:
      - name: Get branch name
        id: get_branch_name
        run: echo "::set-output name=branch_name::${GITHUB_REF#refs/heads/}"
      
      - name: Generate uniq base_tag for node label
        id: generate_base_tag
        run: echo "::set-output name=base_tag::$(head /dev/urandom | tr -dc 'a-z' | fold -w 3 | head -n 1)"

      - name: Trigger Run Smoketests workflow on current branch
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Run Smoketests
          repo: NethermindEth/juno-smoke-tests
          token: ${{ secrets.REPOSITORY_DISPATCH_TOKEN }}
          inputs: '{"base_tag": "${{ steps.generate_base_tag.outputs.base_tag }}", "config_json": "{ \"networks\": [ \"${{ env.NETWORK }}\" ], \"branch\": [ \"${{ steps.get_branch_name.outputs.branch_name }}\" ], \"node_custom_types\": { \"${{ env.NETWORK }}\": \"g6-standard-4\" } }"}'
          ref: main
