on:
  workflow_call:
    inputs:
      docker_image_tag:
        required: true
        type: string
        description: 'Docker image tag of Juno to pull and test.'
    secrets:
      APP_PRIVATE_KEY:
        required: true
        description: 'Private key for the GitHub App used to generate tokens.'
      APP_ID:
        required: true
        description: 'The ID of the GitHub App.'

permissions:
  contents: read
  id-token: write

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: nethermind.jfrog.io
      REPO_DEV: nubia-oci-local-dev
    steps:
      - name: Define Full Image Path
        id: set_image_path
        env:
          DOCKER_TAG: ${{ inputs.docker_image_tag }}
        run: |
          echo "FULL_IMAGE_PATH=${{ env.DOCKER_REGISTRY }}/${{ env.REPO_DEV }}/juno:${DOCKER_TAG}" >> $GITHUB_ENV

      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: "juno,juno-smoke-tests"

      - name: Install JFrog CLI
        id: jfrog
        uses: jfrog/setup-jfrog-cli@ff5cb544114ffc152db9cea1cd3d5978d5074946 # v4.5.11
        env:
          JF_URL: https://${{ env.DOCKER_REGISTRY }}
        with:
          oidc-provider-name: github-nethermindeth

      - name: Login to Registry with OIDC
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ steps.jfrog.outputs.oidc-user }}
          password: ${{ steps.jfrog.outputs.oidc-token }}

      - name: Pull docker image
        run: docker pull ${{ env.FULL_IMAGE_PATH }}

      - name: Checkout Juno Smoke Tests
        uses: actions/checkout@v6
        with:
          repository: NethermindEth/juno-smoke-tests
          token: ${{ steps.generate-token.outputs.token }}

      - name: Run smoke tests
        env:
          TARGET_BLOCK: 100
          TIMEOUT: 10m
          JUNO_PARAMETERS: "--network mainnet --disable-l1-verification"
          JUNO_IMAGE: ${{ env.FULL_IMAGE_PATH }}
        run: |
          cd smoke-tests/node_tests
          go test -v -run TestMonitorNodeSync -args -targetBlock=$TARGET_BLOCK -timeout=$TIMEOUT